---
service:
  internalPort: 27017
  externalPort: 27017

image:
  repository: mongo
  tag: "4.4.3"

volumeMounts:
  name: "mongo-persistent-storage"
  mountPath: "/data/db"

volumes:
  name: "mongo-persistent-storage"
