image: ruby:2.4.2

stages:
  - build
  - test
  - deploy

variables:
  DATABASE_URL: 'mongod://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

test_crawler_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_ui_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy:
  stage: deploy
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
