image: python:3.6

stages:
  - build
  - test
  - deploy

variables:
  DATABASE_URL: 'mongod://mongo/user_posts'

build_job:
  stage: build
  script:
    - echo 'Building'

test_crawler_job:
  stage: test
  services:
    - mongo:latest
  script:
    - cd Dockers/search_engine_crawler
    - pip install -r requirements-test.txt
    - python -m unittest discover -s tests/ 

test_ui_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy:
  stage: deploy
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
