---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rabbitmq.fullname" . }} # search-crawler
  labels:
    app: search-engine
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: rabbitmq
      release: {{ .Release.Name }}
  template:
    metadata:
      name: rabbitmq
      labels:
        app: search-engine
        component: rabbitmq
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }} # funnyfatty/search_crawler:1.0
        name: rabbitmq
        ports:
          - containerPort: {{ .Values.service.internalPort }}
            name: rabbitmq
            protocol: TCP
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmqUser }} # guest
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitmqPassword }} # guest
