---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "search_ui.fullname" . }}
spec:
  backend:
    serviceName: {{ template "search_ui.fullname" . }}
    servicePort: {{ .Values.service.externalPort }}
