---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "search_crawler.fullname" . }} # search-crawler
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: search-crawler
      labels:
        app: search-engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }} # funnyfatty/search_crawler:1.0
        name: search-crawler
        ports:
          - containerPort: {{ .Values.service.internalPort }}
            name: search-crawler
            protocol: TCP
        env:
        - name: MONGO
          value: {{ .Values.mongodbHost }} # crawler-db
        - name: RMQ_HOST
          value: {{ .Values.rabbitmqHost }} # crawler-rabbitmq
