---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: search-engine
    component: rabbitmq
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: search-engine
    component: rabbitmq
